# SPDX-FileCopyrightText: 2024 Helmholtz-Zentrum Dresden - Rossendorf (HZDR)
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileContributor: David Pape

[policies.authors]
source = "https://software-metadata.pub/software-card-policies/example-policies/policies/authors-affiliation.ttl"

[policies.description]
source = "https://software-metadata.pub/software-card-policies/example-policies/policies/description-parameterizable.ttl"
parameters = {description_min_length = 10}

[policies.licenses]
source = "https://software-metadata.pub/software-card-policies/example-policies/policies/licenses-parameterizable.ttl"

[policies.licenses.parameters]
suggested_licenses = [
    "https://spdx.org/licenses/Apache-2.0",
    "https://spdx.org/licenses/GPL-3.0-or-later"
]
